#!/usr/bin/env python3
"""Single registry of every provider wired into this dashboard.

Adding a provider is a one-entry change here (plus one line in each
workflow file and .env.example, and the secret in the GitHub/Vercel UIs).

Field meanings:
  key          stable identifier used by probe_models/generate_site
  label        display name on the site / in provider-check.sh
  env          env var holding the API key / token
  probe_url    chat-completions-style URL used by the probe engine
  auth         how the probe authenticates: "bearer" | "x-goog"
  style        probe payload/URL style: openai | cohere_v2 | gemini | cloudflare
  anonymous_ok True if awareness probing works without a key (llm7 only)
  models_url   models-list URL (used by provider-check.sh and the generic fetcher)
  models_auth  auth for the models URL: "bearer" | "optional" | "none"
  free_suffixes  model-id suffixes marking free models (generic fetcher filter), or None
  color        accent color used by the site
  url          provider homepage
  key_url      where to obtain the key
  fetch        "generic" (use fetch_generic_models) or "custom:<fetch_* name>"
"""

PROVIDERS = [
    {
        "key": "openrouter",
        "label": "OpenRouter",
        "env": "OPENROUTER_API_KEY",
        "probe_url": "https://openrouter.ai/api/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://openrouter.ai/api/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#6366f1",
        "url": "https://openrouter.ai",
        "key_url": "https://openrouter.ai/keys",
        "fetch": "custom:fetch_openrouter",
    },
    {
        "key": "groq",
        "label": "Groq",
        "env": "GROQ_API_KEY",
        "probe_url": "https://api.groq.com/openai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.groq.com/openai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#f59e0b",
        "url": "https://console.groq.com",
        "key_url": "https://console.groq.com/keys",
        "fetch": "custom:fetch_groq",
    },
    {
        "key": "cerebras",
        "label": "Cerebras",
        "env": "CEREBRAS_API_KEY",
        "probe_url": "https://api.cerebras.ai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.cerebras.ai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#10b981",
        "url": "https://cloud.cerebras.ai",
        "key_url": "https://cloud.cerebras.ai/platform",
        "fetch": "custom:fetch_cerebras",
    },
    {
        "key": "gemini",
        "label": "Gemini",
        "env": "GEMINI_API_KEY",
        "probe_url": "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        "auth": "x-goog",
        "style": "gemini",
        "anonymous_ok": False,
        "models_url": "https://generativelanguage.googleapis.com/v1beta/models",
        "models_auth": "none",
        "free_suffixes": None,
        "color": "#3b82f6",
        "url": "https://aistudio.google.com",
        "key_url": "https://aistudio.google.com/apikey",
        "fetch": "custom:fetch_gemini",
    },
    {
        "key": "sambanova",
        "label": "SambaNova",
        "env": "SAMBANOVA_API_KEY",
        "probe_url": "https://api.sambanova.ai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.sambanova.ai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#8b5cf6",
        "url": "https://cloud.sambanova.ai",
        "key_url": "https://cloud.sambanova.ai/",
        "fetch": "custom:fetch_sambanova",
    },
    {
        "key": "cohere",
        "label": "Cohere",
        "env": "COHERE_API_KEY",
        "probe_url": "https://api.cohere.com/v2/chat",
        "auth": "bearer",
        "style": "cohere_v2",
        "anonymous_ok": False,
        "models_url": "https://api.cohere.com/v2/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#ec4899",
        "url": "https://cohere.com",
        "key_url": "https://dashboard.cohere.com/api-keys",
        "fetch": "custom:fetch_cohere",
    },
    {
        "key": "together",
        "label": "Together AI",
        "env": "TOGETHER_API_KEY",
        "probe_url": "https://api.together.ai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.together.ai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#14b8a6",
        "url": "https://api.together.ai",
        "key_url": "https://api.together.ai/settings/api-keys",
        "fetch": "custom:fetch_together",
    },
    {
        "key": "nvidia",
        "label": "NVIDIA NIM",
        "env": "NVIDIA_NIM_API_KEY",
        "probe_url": "https://integrate.api.nvidia.com/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://integrate.api.nvidia.com/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#22c55e",
        "url": "https://build.nvidia.com",
        "key_url": "https://build.nvidia.com/",
        "fetch": "custom:fetch_nvidia",
    },
    {
        "key": "huggingface",
        "label": "HuggingFace",
        "env": "HF_TOKEN",
        "probe_url": "https://router.huggingface.co/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://router.huggingface.co/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#f97316",
        "url": "https://huggingface.co",
        "key_url": "https://huggingface.co/settings/tokens",
        "fetch": "custom:fetch_huggingface",
    },
    {
        "key": "mistral",
        "label": "Mistral",
        "env": "MISTRAL_API_KEY",
        "probe_url": "https://api.mistral.ai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.mistral.ai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#0ea5e9",
        "url": "https://console.mistral.ai",
        "key_url": "https://console.mistral.ai/api-keys/",
        "fetch": "custom:fetch_mistral",
    },
    {
        "key": "github",
        "label": "GitHub Models",
        "env": "GH_MODELS_TOKEN",
        "probe_url": "https://models.inference.ai.azure.com/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://models.inference.ai.azure.com/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#e2e8f0",
        "url": "https://github.com/marketplace/models",
        "key_url": "https://github.com/settings/tokens",
        "fetch": "custom:fetch_github",
    },
    {
        "key": "cloudflare",
        "label": "Cloudflare AI",
        "env": "CLOUDFLARE_API_KEY",
        "probe_url": "https://api.cloudflare.com/client/v4/accounts/{account}/ai/run/{model}",
        "auth": "bearer",
        "style": "cloudflare",
        "anonymous_ok": False,
        "models_url": "https://api.cloudflare.com/client/v4/accounts/{account}/ai/models/search?per_page=5",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#f6821f",
        "url": "https://developers.cloudflare.com/workers-ai/",
        "key_url": "https://dash.cloudflare.com/profile/api-tokens",
        "fetch": "custom:fetch_cloudflare",
    },
    {
        "key": "kluster",
        "label": "Kluster AI",
        "env": "KLUSTER_API_KEY",
        "probe_url": "https://api.kluster.ai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.kluster.ai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#a855f7",
        "url": "https://kluster.ai",
        "key_url": "https://platform.kluster.ai/apikeys",
        "fetch": "custom:fetch_kluster",
    },
    {
        "key": "llm7",
        "label": "LLM7",
        "env": "LLM7_API_KEY",
        "probe_url": "https://api.llm7.io/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": True,
        "models_url": "https://api.llm7.io/v1/models",
        "models_auth": "optional",
        "free_suffixes": None,
        "color": "#facc15",
        "url": "https://llm7.io",
        "key_url": "https://token.llm7.io",
        "fetch": "custom:fetch_llm7",
    },
    {
        "key": "zai",
        "label": "Z.ai (GLM)",
        "env": "ZAI_API_KEY",
        "probe_url": "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://open.bigmodel.cn/api/paas/v4/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#0ea5e9",
        "url": "https://open.bigmodel.cn",
        "key_url": "https://open.bigmodel.cn/usercenter/apikeys",
        "fetch": "custom:fetch_zai",
    },
    {
        "key": "modelscope",
        "label": "ModelScope",
        "env": "MODELSCOPE_API_KEY",
        "probe_url": "https://api-inference.modelscope.cn/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api-inference.modelscope.cn/v1/models",
        "models_auth": "optional",
        "free_suffixes": None,
        "color": "#3b82f6",
        "url": "https://modelscope.cn",
        "key_url": "https://modelscope.cn/my/myaccesstoken",
        "fetch": "custom:fetch_modelscope",
    },
    {
        "key": "kilo",
        "label": "Kilo Code",
        "env": "KILOCODE_API_KEY",
        "probe_url": "https://api.kilo.ai/api/gateway/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.kilo.ai/api/gateway/models",
        "models_auth": "optional",
        "free_suffixes": (":free", "/free"),
        "color": "#f59e0b",
        "url": "https://kilo.code",
        "key_url": "https://kilo.code",
        "fetch": "custom:fetch_kilo",
    },
    {
        "key": "zen",
        "label": "OpenCode Zen",
        "env": "OPENCODE_ZEN_API_KEY",
        "probe_url": "https://opencode.ai/zen/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://opencode.ai/zen/v1/models",
        "models_auth": "optional",
        "free_suffixes": ("-free",),
        "color": "#7c3aed",
        "url": "https://opencode.ai/zen",
        "key_url": "https://opencode.ai/settings/api-keys",
        "fetch": "custom:fetch_zen",
    },
    {
        "key": "ollama",
        "label": "Ollama Cloud",
        "env": "OLLAMA_API_KEY",
        "probe_url": "https://ollama.com/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://ollama.com/v1/models",
        "models_auth": "bearer",
        "free_suffixes": None,
        "color": "#22c55e",
        "url": "https://ollama.com",
        "key_url": "https://ollama.com/settings/keys",
        "fetch": "custom:fetch_ollama",
    },
    {
        "key": "orca",
        "label": "Orca Router",
        "env": "ORCA_API_KEY",
        "probe_url": "https://api.orcarouter.ai/v1/chat/completions",
        "auth": "bearer",
        "style": "openai",
        "anonymous_ok": False,
        "models_url": "https://api.orcarouter.ai/v1/models",
        "models_auth": "bearer",
        "free_suffixes": ("-free", "/free"),
        "color": "#f97316",
        "url": "https://orcarouter.ai",
        "key_url": "https://www.orcarouter.ai/console/billing",
        "fetch": "custom:fetch_orca",
    },
]


if __name__ == "__main__":
    # Emit provider-check.sh loop lines: label|models_url|header|env|optional
    for p in PROVIDERS:
        if p["auth"] == "x-goog":
            header = "x-goog-api-key: $KEY"
        elif p["auth"] == "bearer":
            header = "Authorization: Bearer $KEY"
        else:
            header = ""
        optional = "optional" if p["anonymous_ok"] else "required"
        print("|".join([p["label"], p["models_url"], header, p["env"], optional]))
